[theme]

# Primary accent for interactive elements
primaryColor = "#040d25"

# Background color for the main content area
backgroundColor = "#eace9b"

# Background color for siddebar and most interactive widgets
secondaryBackgroundColor = "#efba80"

# Color used for almost all text
textColor = "#010114"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "serif"
font = "serif"